from enum import Enum, auto


class ChannelMoods(Enum):
    MYSTERIOUS = 'Mysterious'
    HIGH_ENERGY = 'High Energy'
    HUMOROUS = 'Humorous'
    SCANDALOUS = 'Scandalous'
    FEAR_MONGERING = 'Fear Mongering'
    ANGER_INDUCING = 'Anger Inducing'


class SceneTransitions(Enum):
    FADE_IN = auto()
    FADE_OUT = auto()
    CROSS_FADE = auto()
    HARD_CUT = auto()
    SLIDE_UP = auto()
    SLIDE_DOWN = auto()
    SLIDE_LEFT = auto()
    SLIDE_RIGHT = auto()

class YoutubeActions(Enum):
    DELETE_CAPTIONS = 50
    DELETE_CHANNEL_SECTIONS = 50
    DELETE_COMMENTS = 50
    DELETE_PLAYLIST_ITEMS = 50
    DELETE_PLAYLISTS = 50
    DELETE_SUBSCRIPTIONS = 50
    DELETE_VIDEOS = 50
    GET_RATING_VIDEOS = 1
    INSERT_CAPTIONS = 400
    INSERT_CHANNEL_BANNERS = 50
    INSERT_CHANNEL_SECTIONS = 50
    INSERT_COMMENTS = 50
    INSERT_PLAYLIST_ITEMS = 50
    INSERT_PLAYLISTS = 50
    INSERT_SUBSCRIPTIONS = 50
    INSERT_VIDEOS = 1600
    LIST_ACTIVITIES = 1
    LIST_CAPTIONS = 50
    LIST_CHANNEL_SECTIONS = 1
    LIST_CHANNELS = 1
    LIST_COMMENT_THREADS = 1
    LIST_GUIDE_CATEGORIES = 1
    LIST_I18N_LANGUAGES = 1
    LIST_I18N_REGIONS = 1
    LIST_MEMBERS = 1
    LIST_MEMBERSHIPS_LEVELS = 1
    LIST_PLAYLIST_ITEMS = 1
    LIST_PLAYLISTS = 1
    LIST_SEARCH = 100
    LIST_SUBSCRIPTIONS = 1
    LIST_VIDEO_ABUSE_REPORT_REASONS = 1
    LIST_VIDEO_CATEGORIES = 1
    LIST_VIDEOS = 1
    RATE_VIDEOS = 50
    REPORT_ABUSE_VIDEOS = 50
    SET_MODERATION_STATUS_COMMENTS = 50
    SET_THUMBNAILS = 50
    UPDATE_CAPTIONS = 450
    UPDATE_CHANNELS = 50
    UPDATE_COMMENT_THREADS = 50
    UPDATE_PLAYLIST_ITEMS = 50
    UPDATE_PLAYLISTS = 50
    UPDATE_VIDEOS = 50